nelmio_api_doc:
    documentation:
        info:
            title: Tracking Currency Exchange Rates
            description: Testing project
            version: 1.0.0
    areas:
        path_patterns:
            - ^(?!(/doc|/_.+|/)$)
