parameters:
    exchange_rate.lifetime: '%env(int:EXCHANGE_RATE_LIFETIME)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Messenger\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Redis:
        class: Redis
        factory: ['App\Factory\RedisFactory', 'create']
        arguments:
            $host: '%env(string::REDIS_HOST)%'
            $password: '%env(string::REDIS_PASSWORD)%'
